#!/usr/bin/env python3
"""
Prepare a GitHub publication tree from an absolute-path manifest.

Main behavior:
- Read selected files/directories from github_manifest.md.
- Accept absolute paths from multiple filesystems.
- Preserve the directory structure relative to configured source roots.
- Recursively detect local Python imports with ast.
- Copy required local modules into the Git working tree.
- Remove stale generated files from previous runs.
- Never run git add/commit/push automatically.

Expected repository:
    /A/data10/nagura/work/code/themes/MidDepth/OFES_IdealExp/code-public

Python import root:
    /A/data10/nagura/work/code
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


DEFAULT_REPO_ROOT = Path(
    "/A/data10/nagura/work/code/themes/MidDepth/OFES_IdealExp/code-public"
)
DEFAULT_MANIFEST = DEFAULT_REPO_ROOT / "github_manifest.md"

# Local Python modules are resolved from these roots.
# The first matching root is used.
PYTHON_IMPORT_ROOTS = [
    Path("/A/data10/nagura/work/code"),
]

# Map source filesystem roots to destinations inside the Git repository.
#
# /A/data10/nagura/work/code/foo/bar.py
#   -> <repo>/foo/bar.py
#
# /S/data01/project/foo.dat
#   -> <repo>/external/S/data01/project/foo.dat
#
# Add more mappings here if additional storage roots are needed.
SOURCE_MAPPINGS = [
    (Path("/A/data10/nagura/work/code"), Path(".")),
    (Path("/S/data01"), Path("OGCM_Exp/S/data01")),
]

# Paths inside the repository that this script must never delete.
PROTECTED_REPO_PATHS = {
    Path(".git"),
    Path("github_manifest.md"),
    Path("publish_prepare.py"),
}

# State file used to know which files were generated by the previous run.
STATE_FILE = Path(".publish_prepare_state")

# Common generated/cache directories that should not be copied when a
# directory is listed in the manifest.
IGNORED_DIR_NAMES = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".ipynb_checkpoints",
}

IGNORED_FILE_SUFFIXES = {
    ".pyc",
    ".pyo",
}


@dataclass(frozen=True)
class SelectedFile:
    source: Path
    reason: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare selected files and local Python dependencies for GitHub."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help=f"Manifest file (default: {DEFAULT_MANIFEST})",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=DEFAULT_REPO_ROOT,
        help=f"Git working tree (default: {DEFAULT_REPO_ROOT})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned changes without modifying files.",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not remove files generated by the previous run.",
    )
    return parser.parse_args()


def read_manifest(path: Path) -> list[Path]:
    """
    Read absolute paths from a Markdown manifest.

    Accepted examples:
        /A/data10/nagura/work/code/common/foo.py
        - /A/data10/nagura/work/code/themes/MidDepth/...
        * `/S/data01/project/data/example.nc`

    Empty lines, headings, comments, and normal prose are ignored.
    """
    entries: list[Path] = []

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()

        if not line or line.startswith("#") or line.startswith("<!--"):
            continue

        # Remove common Markdown list markers.
        if line.startswith(("- ", "* ", "+ ")):
            line = line[2:].strip()

        # Remove Markdown code quoting.
        if line.startswith("`") and line.endswith("`") and len(line) >= 2:
            line = line[1:-1].strip()

        # Only absolute filesystem paths are interpreted as manifest entries.
        if not line.startswith("/"):
            continue

        entries.append(Path(line).expanduser())

    return entries


def is_ignored(path: Path) -> bool:
    if any(part in IGNORED_DIR_NAMES for part in path.parts):
        return True
    if path.suffix in IGNORED_FILE_SUFFIXES:
        return True
    return False


def expand_manifest_entries(entries: Iterable[Path]) -> list[SelectedFile]:
    selected: dict[Path, SelectedFile] = {}

    for entry in entries:
        entry = entry.resolve()
        print('entry = ',entry)

        if not entry.exists():
            raise FileNotFoundError(f"Manifest entry does not exist: {entry}")

        if entry.is_file():
            if not is_ignored(entry):
                selected[entry] = SelectedFile(entry, "manifest")
            continue

        if entry.is_dir():
            for path in sorted(entry.rglob("*")):
                if path.is_file() and not is_ignored(path):
                    selected[path.resolve()] = SelectedFile(
                        path.resolve(),
                        f"manifest directory: {entry}",
                    )
            continue

        raise ValueError(f"Unsupported manifest entry: {entry}")

    return list(selected.values())


def destination_for_source(source: Path, repo_root: Path) -> Path:
    """
    Convert an absolute source path to a path inside the Git repository.
    """
    source = source.resolve()

    for source_root, repo_prefix in SOURCE_MAPPINGS:
        source_root = source_root.resolve()
        try:
            relative = source.relative_to(source_root)
        except ValueError:
            continue

        destination = (repo_root / repo_prefix / relative).resolve()

        # Prevent accidental writes outside the repository.
        try:
            destination.relative_to(repo_root.resolve())
        except ValueError as exc:
            raise RuntimeError(
                f"Destination escaped repository root: {destination}"
            ) from exc

        return destination

    raise ValueError(
        "No SOURCE_MAPPINGS entry matches source path:\n"
        f"  {source}\n"
        "Add an explicit source-root mapping near the top of publish_prepare.py."
    )


def parse_python_imports(path: Path) -> list[tuple[int, str | None, list[str]]]:
    """
    Return import statements in a normalized representation.

    Each tuple is:
        (relative_level, module_name, imported_names)

    Examples:
        import common.foo
            -> (0, "common.foo", [])

        from common.foo import bar
            -> (0, "common.foo", ["bar"])

        from .utils import foo
            -> (1, "utils", ["foo"])
    """
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        text = path.read_text(encoding="utf-8", errors="replace")

    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError as exc:
        print(f"WARNING: Could not parse Python file: {path}: {exc}", file=sys.stderr)
        return []

    imports: list[tuple[int, str | None, list[str]]] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.append((0, alias.name, []))

        elif isinstance(node, ast.ImportFrom):
            names = [alias.name for alias in node.names if alias.name != "*"]
            imports.append((node.level, node.module, names))

    return imports


def module_candidates(import_root: Path, dotted_name: str) -> list[Path]:
    """
    Return possible files for an absolute dotted module name.
    """
    module_path = import_root.joinpath(*dotted_name.split("."))

    candidates = [
        module_path.with_suffix(".py"),
        module_path / "__init__.py",
    ]

    return [p.resolve() for p in candidates if p.is_file()]


def package_parts_for_file(path: Path, import_root: Path) -> list[str] | None:
    """
    Return package components for a Python file relative to an import root.

    Example:
        import_root = /.../code
        path = /.../code/themes/a/foo.py
        -> ["themes", "a"]
    """
    try:
        relative = path.resolve().relative_to(import_root.resolve())
    except ValueError:
        return None

    if path.name == "__init__.py":
        return list(relative.parent.parts)

    return list(relative.parent.parts)


def resolve_absolute_module(dotted_name: str) -> list[Path]:
    results: list[Path] = []

    for root in PYTHON_IMPORT_ROOTS:
        results.extend(module_candidates(root, dotted_name))

    return deduplicate_paths(results)


def resolve_relative_module(
    importer: Path,
    level: int,
    module_name: str | None,
) -> list[Path]:
    results: list[Path] = []

    for root in PYTHON_IMPORT_ROOTS:
        package_parts = package_parts_for_file(importer, root)
        if package_parts is None:
            continue

        # For "from .x", level=1 means current package.
        climb = level - 1
        if climb > len(package_parts):
            continue

        base_parts = package_parts[: len(package_parts) - climb]

        if module_name:
            base_parts += module_name.split(".")

        if not base_parts:
            continue

        dotted = ".".join(base_parts)
        results.extend(module_candidates(root, dotted))

    return deduplicate_paths(results)


def resolve_from_import_members(
    base_modules: Iterable[Path],
    imported_names: Iterable[str],
) -> list[Path]:
    """
    Handle cases such as:
        from common import helper

    where helper may be common/helper.py rather than an attribute defined
    directly in common/__init__.py.
    """
    results: list[Path] = []

    for base in base_modules:
        if base.name == "__init__.py":
            package_dir = base.parent
        elif base.suffix == ".py":
            # A regular module cannot contain child modules.
            continue
        else:
            continue

        for name in imported_names:
            member_path = package_dir / name
            py_file = member_path.with_suffix(".py")
            init_file = member_path / "__init__.py"

            if py_file.is_file():
                results.append(py_file.resolve())
            if init_file.is_file():
                results.append(init_file.resolve())

    return deduplicate_paths(results)


def resolve_imports(importer: Path) -> list[Path]:
    dependencies: list[Path] = []

    for level, module_name, imported_names in parse_python_imports(importer):
        if level == 0:
            if not module_name:
                continue
            base_modules = resolve_absolute_module(module_name)
        else:
            base_modules = resolve_relative_module(importer, level, module_name)

        dependencies.extend(base_modules)
        dependencies.extend(
            resolve_from_import_members(base_modules, imported_names)
        )

    return deduplicate_paths(dependencies)


def add_parent_init_files(path: Path) -> list[Path]:
    """
    Include existing __init__.py files between a module and its import root.
    """
    results: list[Path] = []

    for root in PYTHON_IMPORT_ROOTS:
        root = root.resolve()
        try:
            relative = path.resolve().relative_to(root)
        except ValueError:
            continue

        current = root
        for part in relative.parent.parts:
            current = current / part
            init_file = current / "__init__.py"
            if init_file.is_file():
                results.append(init_file.resolve())

    return deduplicate_paths(results)


def collect_python_dependencies(
    initial_files: Iterable[SelectedFile],
) -> dict[Path, SelectedFile]:
    """
    Recursively collect Python modules imported from PYTHON_IMPORT_ROOTS.
    """
    selected: dict[Path, SelectedFile] = {
        item.source.resolve(): item for item in initial_files
    }

    queue = [
        item.source.resolve()
        for item in initial_files
        if item.source.suffix == ".py"
    ]
    parsed: set[Path] = set()

    while queue:
        importer = queue.pop(0)

        if importer in parsed:
            continue
        parsed.add(importer)

        for dependency in resolve_imports(importer):
            if dependency not in selected:
                selected[dependency] = SelectedFile(
                    dependency,
                    f"imported by {importer}",
                )

            if dependency.suffix == ".py" and dependency not in parsed:
                queue.append(dependency)

            for init_file in add_parent_init_files(dependency):
                if init_file not in selected:
                    selected[init_file] = SelectedFile(
                        init_file,
                        f"package initializer for {dependency}",
                    )
                if init_file not in parsed:
                    queue.append(init_file)

    return selected


def deduplicate_paths(paths: Iterable[Path]) -> list[Path]:
    seen: set[Path] = set()
    result: list[Path] = []

    for path in paths:
        resolved = path.resolve()
        if resolved not in seen:
            seen.add(resolved)
            result.append(resolved)

    return result


def file_digest(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)

    return digest.hexdigest()


def files_are_identical(source: Path, destination: Path) -> bool:
    if not destination.is_file():
        return False

    try:
        if source.stat().st_size != destination.stat().st_size:
            return False
    except OSError:
        return False

    return file_digest(source) == file_digest(destination)


def load_previous_state(repo_root: Path) -> set[Path]:
    path = repo_root / STATE_FILE

    if not path.is_file():
        return set()

    result: set[Path] = set()

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            result.add(Path(line))

    return result


def save_state(repo_root: Path, relative_paths: Iterable[Path]) -> None:
    path = repo_root / STATE_FILE
    lines = sorted(str(p) for p in relative_paths)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def is_protected_repo_path(relative: Path) -> bool:
    if relative in PROTECTED_REPO_PATHS:
        return True

    return any(
        protected in relative.parents
        for protected in PROTECTED_REPO_PATHS
        if protected != Path(".git")
    )


def prepare_repository(
    selected: dict[Path, SelectedFile],
    repo_root: Path,
    *,
    dry_run: bool,
    clean: bool,
) -> None:
    repo_root = repo_root.resolve()
    repo_root.mkdir(parents=True, exist_ok=True)

    destination_map: dict[Path, SelectedFile] = {}

    for source, item in selected.items():
        destination = destination_for_source(source, repo_root)
        relative = destination.relative_to(repo_root)

        if relative == Path("."):
            raise RuntimeError(f"Invalid repository destination for {source}")

        # Never allow generated content to overwrite control files.
        if is_protected_repo_path(relative):
            raise RuntimeError(
                f"Selected source would overwrite protected repository path: "
                f"{relative} <- {source}"
            )

        previous = destination_map.get(relative)
        if previous and previous.source != source:
            raise RuntimeError(
                "Two source files map to the same repository path:\n"
                f"  {previous.source}\n"
                f"  {source}\n"
                f"  -> {relative}"
            )

        destination_map[relative] = item

    desired_paths = set(destination_map)
    previous_paths = load_previous_state(repo_root)

    if clean:
        stale_paths = sorted(previous_paths - desired_paths)
    else:
        stale_paths = []

    added = 0
    updated = 0
    unchanged = 0
    deleted = 0

    for relative in stale_paths:
        if is_protected_repo_path(relative):
            continue

        destination = repo_root / relative

        if destination.is_file() or destination.is_symlink():
            print(f"DELETE   {relative}")
            deleted += 1
            if not dry_run:
                destination.unlink()

    # Remove empty directories left by stale files.
    if clean and not dry_run:
        directories = sorted(
            (p for p in repo_root.rglob("*") if p.is_dir()),
            key=lambda p: len(p.parts),
            reverse=True,
        )
        for directory in directories:
            if directory == repo_root or ".git" in directory.parts:
                continue
            try:
                directory.rmdir()
            except OSError:
                pass

    for relative, item in sorted(destination_map.items(), key=lambda kv: str(kv[0])):
        source = item.source
        destination = repo_root / relative

        if destination.exists() and files_are_identical(source, destination):
            print(f"OK       {relative}")
            unchanged += 1
            continue

        action = "UPDATE" if destination.exists() else "ADD"
        print(f"{action:<8} {relative}")
        print(f"         <- {source}")
        print(f"         reason: {item.reason}")

        if action == "ADD":
            added += 1
        else:
            updated += 1

        if not dry_run:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)

    print()
    print(
        f"Summary: added={added}, updated={updated}, "
        f"deleted={deleted}, unchanged={unchanged}"
    )

    if not dry_run:
        save_state(repo_root, desired_paths)


def main() -> int:
    args = parse_args()

    manifest = args.manifest.resolve()
    repo_root = args.repo.resolve()

    if not manifest.is_file():
        print(f"ERROR: Manifest not found: {manifest}", file=sys.stderr)
        return 2

    print(f"Manifest: {manifest}")
    print(f"Repository: {repo_root}")
    print(f"Mode: {'dry-run' if args.dry_run else 'write'}")
    print()

    entries = read_manifest(manifest)

    if not entries:
        print("ERROR: No absolute paths were found in the manifest.", file=sys.stderr)
        return 2

    initial_files = expand_manifest_entries(entries)
    selected = collect_python_dependencies(initial_files)

    print(f"Manifest-selected files: {len(initial_files)}")
    print(f"Files after dependency collection: {len(selected)}")
    print()

    prepare_repository(
        selected,
        repo_root,
        dry_run=args.dry_run,
        clean=not args.no_clean,
    )

    print()
    print("Next recommended commands:")
    print(f"  cd {repo_root}")
    print("  git status")
    print("  git diff --stat")
    print("  git diff")
    print("  git add -A")
    print('  git commit -m "Update published code"')
    print("  git push")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
