#! /bin/csh -f
#
#     run script for driving the "topog_m.F" module
#
#     consult manual for available options.


set MOMpath = /S/home00/G4006/y0003/OFES_TOOL/MOM3_PACI
set WORK = /S/data01/G4006/y0330/data/ofes_exp/tmp
set MOM_update = /S/home00/G4006/y0003/OFES_TOOL/TOPOG/TOPO_NP04
set MOM_mine = /S/data01/G4006/y0330/code/ofes/topo/saved_settings/box
set OUT = /S/data01/G4006/y0330/data/ofes_exp/settings/box_cyclic_BottomDrag_ReadIC/topog

echo " "
echo " =>executing: run_topog_m"
echo " "

set NETCDF = "" # don't produce netcdf output

set NETCDFlib = ""

set TOPOGRAPHY = '-Detopo_kmt'    # 1/12 deg NGDC topography (not supplied)

set OPTIONS = '-Ddrive_topog -Dread_my_grid'
#set OPTIONS = '-Ddrive_topog -Dread_my_grid -Dfill_isolated_cells -Dcyclic'

#set OTHER_OPTIONS = ' -Dwrite_my_kmt -Dpartial_cell -DOFES_05_Ind'
set OTHER_OPTIONS = ' -Dwrite_my_kmt -DOFES_05_Ind'              #  for box_cyclic_BottomDrag_ReadIC

set ALL_OPTIONS = ($OPTIONS $OTHER_OPTIONS $TOPOGRAPHY $NETCDF -I/usr/local/include/)

echo OPTION LIST: $ALL_OPTIONS
echo " "

#
# if (-d $WORK) then
#   /bin/rm -r $WORK
# endif
mkdir $WORK

set list = (taskrows.h param.h tmngr.h vers.h stdunits.h derived_options.h)
set list = ($list coord.h util.F iomngr.F iomngr.h size_check.F)
set list = ($list pconst.h iomngr.F iomngr.h size_check.F)
# set list = ($list grids.F size.h diag.h topog_m.F)
set list = ($list grids.F size.h diag.h)
set listF90 = (mpp.F90 mpp_domains.F90 mpp_io.F90 datamod.F90 mom3mpp.F90)

echo "=>Copying the following files from $MOMpath to $WORK"
foreach file ($list)
  echo $file
  cp "$MOMpath/$file" $WORK
end
foreach file ($listF90)
  echo $file
  cp "$MOMpath/$file" $WORK
end
cp $MOM_update/grids.F $WORK
#cp $MOM_mine/grids.F $WORK
#cp $MOM_mine/size.h $WORK
cp $OUT/size.h $WORK
cp $MOM_mine/topog_m.F $WORK
#cp $MOM_mine/util.F $WORK
cp $MOM_update/util_l100.F $WORK/util.F
#cp $MOM_mine/util_l100.F $WORK/util.F


if ("$TOPOGRAPHY" == "-Detopo_kmt") then 
 echo " ETOPO5 (37 million words) is not available from GFDL"
 echo " The ETOPO5 dataset can be purchased from the"
 echo " Marine Geology and Geophysics Division of the"
 echo " National Geophysical Data Center."
# cp dtm5_d.bin $WORK
endif

if ("$TOPOGRAPHY" == "-Dscripps_kmt") then
  set SCRIPPS_PATH = $MOMpath
  if  (! -r $SCRIPPS_PATH/scripps.top) then
    echo '=>Error: file "scripps.top" could not be found '
    echo '         when using the scripps_kmt option'
    echo '         change the SCRIPPS_PATH in run_topog_m to point to it'
    exit
  else
    echo " copying SCRIPPS topography from $SCRIPPS_PATH/scripps.top"  
    cp $SCRIPPS_PATH/scripps.top $WORK
  endif
endif

cd $WORK
rm $WORK/*.o $WORK/*.mod

# source /local/f90/3.1.0.0
echo "=>compiling..."
foreach file ($listF90)
      nfort -c -fdefault-integer=8 -fdefault-real=8 $ALL_OPTIONS  $file
#      f90 -c -ew -EP $ALL_OPTIONS  $file
end
    nfort -c -fdefault-integer=8 -fdefault-real=8 $ALL_OPTIONS $NETCDFlib topog_m.F
    nfort -fdefault-integer=8 -fdefault-real=8 $ALL_OPTIONS $NETCDFlib *.o
#    f90 -c -ew -EP $ALL_OPTIONS $NETCDFlib topog_m.F
#    f90 -ew $ALL_OPTIONS $NETCDFlib *.o
    mv a.out topog_m.out

echo "=> Done"

#rm *.o *.mod *.F *.h *.F90

set RESFILE = results_topog
setenv F_FF06 $RESFILE

setenv VE_FORT_UFMTENDIAN ALL
#setenv VE_FORT_RECLUNIT WORD    #  This line should be commented out
setenv VE_ACC_IO 1

ln -s $OUT/grid.dta.out $WORK/grid.dta
ln -s /S/data01/G4006/y0003/DATASET/TOPOG/ETOPO1/etopo1.dbl etopo1.dbl

cp $OUT/kmt.dta .
#./topog_m.out
#
## copy result files to TOPOG directory
#mv -v results_topog $OUT
#mv -v ht.dta $OUT
#diff kmt.dta $OUT/kmt.dta

