#! /bin/csh -f
echo " "
echo "=>executing: run_grids"
echo " "
#
# script for running the "grids.F" module to generate a grid
#
#
#     Consult the manual for other options
#


set OPTIONS = '-Ddrive_grids -Dgenerate_a_grid -Dwrite_my_grid'
#set OPTIONS = '-Ddrive_grids -Dgenerate_a_grid -Dwrite_my_grid -Dcyclic'   #  box_cyclic
#c00/3/16 set OPTIONS = '-Ddrive_grids -Dgenerate_a_grid -Dcyclic'
set OTHER_OPTIONS = ' '

set ALL_OPTIONS = ($OPTIONS $OTHER_OPTIONS)
echo OPTION LIST: $ALL_OPTIONS
echo " "

set MOMpath1 = /S/data01/G4006/y0330/code/ofes/src/OFES/OFES_25SEP02/
set MOMpath2 = /S/data01/G4006/y0330/code/ofes/src/OFES/SeaIce/
set GRDpath = /S/data01/G4006/y0330/code/ofes/topo/saved_settings/box
set WORK = /S/data01/G4006/y0330/data/ofes_exp/tmp
set OUTPUT = /S/data01/G4006/y0330/data/ofes_exp/settings/box_cyclic/topog/

mkdir $WORK
cd $WORK

#cp $MOMpath/grids.F $WORK
cp $GRDpath/grids.F $WORK

if (! -r grids.F) then
  echo '=>Error: need to have "grids.F" in this UPDATES directory'
  echo '         copy "grids.F" to this directory and make modifications here'
  exit
endif

echo "=>Grabbing sources from $MOMpath1"
set list = (stdunits.h iomngr.F iomngr.h derived_options.h)
foreach file ($list)
  echo $file
  cp $MOMpath1/$file $WORK
end

set list = util.F
foreach file ($list)
  echo $file
  cp $MOMpath2/$file $WORK
end

# echo "=>Grabbing sources from $MOMpath"
# set list = (stdunits.h util.F iomngr.F iomngr.h derived_options.h)
# foreach file ($list)
#   echo $file
#   cp $MOMpath/$file $WORK
# end

if (-r grid.dta) then
  echo copying grid.dta.out
  cp grid.dta.out $WORK/grid.dta
endif
cd $WORK

echo "=>compiling..."
nfort -fdefault-integer=8 -fdefault-real=8 $ALL_OPTIONS grids.F

setenv VE_FORT_UFMTENDIAN ALL
setenv VE_FORT_RECLUNIT WORD
setenv VE_ACC_IO 1

echo "=> running...results are being written to results_grids"
./a.out > $OUTPUT/results_grids

if (-r grid.dta.out) then
 echo " "
 echo "=> Constructed: grid.dta.out"
 mv grid.dta.out $OUTPUT
endif

rm *.F *.h

cd $OUTPUT
#/bin/rm -r $WORK

echo " "
tail results_grids

echo " "
echo "=> Done"
